# Generated by Django 3.2.21 on 2023-09-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
