# Generated by Django 3.2.21 on 2023-09-09 11:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_directory', '0003_alter_shop_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo_image',
            field=cloudinary.models.CloudinaryField(default='logo-placeholder', max_length=255, verbose_name='logo'),
        ),
    ]
